language: python
os:
- linux
python:
- '3.4'
- '3.5'
- '3.6'
script:
- python -m pytest tests/ --cov=papis_zotero
install:
- pip install setuptools
- pip install python-coveralls
- pip install pytest
- pip install pytest-cov==2.5.0
- pip install -e .
after_success:
- coveralls
